#+title: Races
#+startup: inlineimages

* Races
The races within Naurrnen are fairly equal. Although Aelves are known for their skills in magic, music, and crafting instruments and enchanted items, that does not mean one will find elves doing hard labor, exercising what strength they have. Orcs are generally favored for that sort of labor, as they tend to be more physically suited for the task. But not every Orc is physically built for this task, as not every Anashim is well suited to the arts. Their are Orcs who take an interest in magic or music, as well. They are generally not as well suited as the Aelves, but that is not to say, their are not Orcs that have better ears, or eyes than many Aelves, or better minds for magic. These exceptions are generally blamed on half-breeds. Half-breeding has become so common in the age of man, no one really knows for sure who is a half-breed, or if one, who might think themselves as a pure-bred, is really a fourth or fifth generation mixed breed. What separates the races more than anything are their cultural identities.
** Languages
*** Adaman, the trade tongue
Adaman is the (almost) universal tongue of Naurrnen. It is used amongst merchants, and mostly widely spoken in everyday communication within the Gran Imperio.
*** Hallashim, language of the Anashim
