#+title: The Discovery Of Elia
#+startup: inlineimages

* The Discovery of Elias
** Introduction
Elias Vorndur, an Edama Archive Guild scholar from Ornasion, set up a team of scholars and explorers to investigate a portal in one of the ancient Amearen cities in the Kaukloutan desert, called Aurunian, which layed just north of the mountains that separate the jungles of Vilesia and the Kouklatan desert, and also several pisecs north of Siyam Nagasi, the capital city of the Principality of Vilesia. The portal is said to be one that reaches the heavenly realm of the gods. The last expidition there had taken place several hundred years ago, and even though the party returned mostly intact, very little was actually recorded in what they found. Elias was going to put this mystery to rest, once and for all.

** Outline
*** Portal Discovery
The party travels several stories underground before reaching the portal. They open their tomes of what is known of the ancient Amearan tongue and after several days, figure out how to activate the portal. Blue light shimmering the darknes and swirling around the portal's entrance, the party steps through to the other side. They enter a room made of metal, and lights that required no candle wax or oil. The windows of the room appeared to be viewing ports into the heavens. They could see spheres in the celestial realm, including Ora, the giant sphere in Naurrnen's sky, some of whom call "moon" and Naurrnen's two suns, like bright disks, yet darkness all around them, like something in the heavens was immune to their light, even though they appeared brighter than they did from Naurrnen.
*** The Strange Throne
Walking further down the hall in this metal room, they found a throne that looked more like designed for function rather than for glorious majesty. They noticed the Amearan runes eched in the arm of the throne. Elias looked up at the other party members with a knowing smile, "this... oh, this!" He remembered one of the ancient Amearan cantations that he had spent most of his career deciphering, and with a click of a button, the thrown moned into life. Light and switches on the throne came to life. Ellias eager to try this unique device, sat on the thrown, entered an Amearan script he had prepared for this moment, and then.... the spherical door, encloses around the throne encaseing Elias in the chair. A view port in front of him, enables to view the others from his expidition. But they are not moving normally, but they suddenly appear to be moving very fast. Inhumanly fast. They look like they are trying to fre Elias from the sphere, but they are moving far too fast. Wait, where are they going? "They are leaving me here!? Why?"
*** A Strange Land
Elias' panic is interrupted as he seems to have transported somewhere away from his spherical trap. But he is also no longer alone. He observes two Adama ment wearing clothing he has never seen before. They were both wearing the same outfit and had goggles on their foreheads. "Hello? Who are you?" asked Elias. The men stopped what they were doing and turned to look at Elias with a rather astonished look on their faces. They responded, seemingly friendly, but Elias could not understand what they were saying.
