#+title: Races
#+startup: inlineimages
#+include: navbar.org
** Primary Races
The races within Naurrnen are fairly equal. Although Elves are known for their skills in magic, music, and crafting instruments and enchanted items, that does not mean one will find elves doing hard labor, exercising what strength they have. Orcs are generally favored for that sort of labor, as they tend to be more physically suited for the task. But not every Orc is physically built for this task, as not every Elf is well suited to the arts. Their are Orcs who take an interest in magic or music, as well. They are generally not as well suited as the Elves, but that is not to say, their are not Orcs that have better ears, or eyes than many Elves, or better minds for magic. These exceptions are generally blamed on half-breeds. Half-breeding has become so common in the age of man, no one really knows for sure who is a half-breed, or if one, who might think themselves as a pure-bred, is really a fourth or fifth generation mixed breed. What separates the races more than anything are their cultural identities.
**** Anashim or Elf
***** Language
Anashim language has several dialects. The most common being that of the Hallashim.
***** Anashim Sub-races
1. High Anashim: Hallashim
2. Wood Anashim: Taurashim
3. Dark Anashim: Durashim
4. Cavern Anashim: Gathashim
***** Strengths
1. Magic
2. Art
3. Architecture
4. Music
5. Crafts
   - Magical items
   - Musical instruments
***** Pantheon
| *Anor*   | Highest father of vengeance.                    |
| *Ithil*  | Highest mother of justice. The great protector. |
| *Gladys* | Goddess of nature.                              |
| *Gurth*  | God of the underworld. Friend of the dead.      |
| *Nostia* | Goddess of fertility.                           |
**** Adama or Man
***** Language
Men's language had been historically Hallashim, as man had been the slaves of certain High Elf empires. But they did have a language of their own that differentiated them from their captors. That slave language evolved into a full-blown Adaman language or language of man. That language became known by the early third era as Malairt or "trade" language.
***** Sub-races
1. Dark man: Durama
2. Red man: Edama
3. Pale man: Palama
***** Strengths
1. Multi-purpose
2. Rational
***** Pantheon
| *Dagda*     | Highest father vengeance and justice.     |
| *Morrigaan* | Highest mother, nuture and nature.        |
| *Orown*     | God of the underworld.                    |
| *Brigid*    | Goddess of art, beauty, and fertility.    |
| *Bres*      | Man king who was exalted to the pantheon. |
**** Orpa
Known in elvish as Osunus, and to the humans as Orcs.
***** Strengths
1. Fighters
2. Manual labor
3. Crafts
   - Blacksmithing
   - Metal/ore work
***** Pantheon
| *Gadajok*  | Highest god. God of vengeance.                   |
| *Hann*     | Highest mother. Goddess of nature and fertility. |
| *Vras*     | God of the dead.                                 |
| *Beatrice* | Goddess of fertility.                            |
| *Nadgaj*   | God of war. God of combat.                       |
** Secondary Races
**** Mochveneba
Mochveneba or "ghost people" are a minority ethnicity within Naurrnen. They are elf-like, in that they share many of the features that elven folk have, but they are well known for their physical prowness. Their skin is a deep red, with stripes. Similar to tiger stripes. In fact, legend outside the Mochveneba tribes, say they are crossbred elves with tigers. In reality, they are more than likely half-breeds. More than likely, half-elf, and half-something else. They have unusual stamina, so some speculate half-orc, though their uncommon beauty seems to indicate otherwise.

The Mochveneba tribes are religious, and perhaps to most of the civilized world, somewhat superstitious. Mochveneba are spiritual and do not generally pursue material wealth. Those that do, are coveted for their beauty and brute strength.
***** Strengths
1. Enchanting weapons and items.
2. Known for physical strength.
3. Warlike, but peace-loving.
***** Pantheon
Unknown

** Languages
*** Adaman, the trade tongue
Adaman is the (almost) universal tongue of Naurrnen. It is used amongst merchants, and mostly widely spoken in everyday communication within the Gran Imperio.
*** Hallashim, language of the Elves
