#+title: Fantasy Feeder

* The World of Naurrnen
** History
*** Eras
**** First Era .... -  1999
***** Pre-recorded History to the first histories
This is Naurrnen's pre-history. It is often referred to in reference to histories and oral traditions that date earlier than when the first recorded era began. Some time, during this era, was the time of the Amearans, or "the ancient ones". A civilization that is believed to have been far more advanced technologically and magically than any civilization after it. So much so, that many believe they were gods or sent from the gods. No one knows what became of them. Many believe they were swooped up into the seventh heaven, upon completing their bidding for the gods. They left what remains of their ancient civilization to teach the people of Naurrnen wisdom and the nature of the gods. But they wrote in a script not familiar to anyone.
**** Second Era 2000 - 4000
***** Eleven Empire(s)
The High Aelves of Áyliaremma (the two trees) united the various tribes into nation states, and then into mighty empires. They were skilled linguists and managed to discover enough of the ancient Amearan language to form a crude understanding of some simple terms that may or may not be accurate translations. They did the best they could without a Philosopher's stone, and advanced Naurrnen's understanding of the language further than any other culture in history.
The Aelves of Áyliaremma made some great archeological discoveries of Amearan technology and lore (including the deciphering of some Amerean script), but wanted to keep this knowledge from other races on Naurrnen, whom they had enslaved for most of this period.
The most dominant of the Anashim empires was Aerithia.
The Aelves of Áyliaremma desired to both preserve what they learned from the Amearans, and encrypt what they have learned to keep their secrets from being learned by the other races. One of the most famous tomes, was title "The Ameara" or the "The Ancient Ones". In it is found a mixture of intriguing historical antedotes that may or may not be correct, tripe geographic details mixed with obscure poetry. The poetry is said to contain the secrets of the Amearans that the Aelves had learned. Falashas cryptic messages are just as lost to the Aelves of the third era, as it is to all the other races.
Bayetti Falasha was an elven scholar, dated as far back as the early second era. She was a court scholar of the great Anashim empire. She wrote many books on philosophy and poetry that are still used extensively and held in the highest regard amongst Anashim folk. Bayetti is, perhaps, the best known scholar of Naurnen's ancient history.
***** Decline of a mighty empire
Elira Naethanor, an esteemed Hallashim of the Eärendelion lineage in Áyliaremma, and Cormac Naethanor, an Adama slave under Aerithia's reign, both served pivotal roles in the downfall of the Anashim Empire. Their clandestine relationship, which blossomed at Laurië Citime, led them to question the empire's oppressive ethics. Risking persecution, they united their intellectual and revolutionary passions, joining a larger movement aimed at emancipating slaves and political prisoners. Their combined defiance and strategies not only labeled them as traitors but also spearheaded the rise of the Gran Imperio, a pluralistic realm that replaced the Anashim hegemony and reshaped Naurrnen's historical trajectory.
**** Third Era 4000 - 5000+

***** Empire of man
The beginning of the reign of man. Men superseded elves, and in doing so, try to build a more pluralistic society, incorporating all races, but unifying them under man's religion.
** Races
*** Primary Races
The races within Naurrnen are fairly equal. Although Aelves are known for their skills in magic, music, and crafting instruments and enchanted items, that does not mean one will find elves doing hard labor, exercising what strength they have. Orcs are generally favored for that sort of labor, as they tend to be more physically suited for the task. But not every Orc is physically built for this task, as not every Aelf is well suited to the arts. Their are Orcs who take an interest in magic or music, as well. They are generally not as well suited as the Aelves, but that is not to say, their are not Orcs that have better ears, or eyes than many Aelves, or better minds for magic. These exceptions are generally blamed on half-breeds. Half-breeding has become so common in the age of man, no one really knows for sure who is a half-breed, or if one, who might think themselves as a pure-bred, is really a fourth or fifth generation mixed breed. What separates the races more than anything are their cultural identities.
**** Anashim or Aelf
***** Language
Anashim language has several dialects. The most common being that of the Hallashim.
***** Anashim Sub-races
1. High Anashim: Hallashim
2. Wood Anashim: Taurashim
3. Dark Anashim: Durashim
4. Cavern Anashim: Gathashim
***** Strengths
1. Magic
2. Art
3. Architecture
4. Music
5. Crafts
   - Magical items
   - Musical instruments
***** Pantheon
| *Anor*   | Highest father of vengeance.                    |
| *Ithil*  | Highest mother of justice. The great protector. |
| *Gladys* | Goddess of nature.                              |
| *Gurth*  | God of the underworld. Friend of the dead.      |
| *Nostia* | Goddess of fertility.                           |
**** Adama or Man
***** Language
Men's language had been historically Hallashim, as man had been the slaves of certain High Aelf empires. But they did have a language of their own that differentiated them from their captors. That slave language evolved into a full-blown Adaman language or language of man. That language became known by the early third era as Malairt or "trade" language.
***** Sub-races
1. Dark man: Durama
2. Red man: Edama
3. Pale man: Palama
***** Strengths
1. Multi-purpose
2. Rational
***** Pantheon
| *Dagda*     | Highest father vengeance and justice.     |
| *Morrigaan* | Highest mother, nuture and nature.        |
| *Orown*     | God of the underworld.                    |
| *Brigid*    | Goddess of art, beauty, and fertility.    |
| *Bres*      | Man king who was exalted to the pantheon. |
**** Orpa
Known in Hallashim as Osunus, and to the humans as Orpas.
***** Strengths
1. Fighters
2. Manual labor
3. Crafts
   - Blacksmithing
   - Metal/ore work
***** Pantheon
| *Gadajok*  | Highest god. God of vengeance.                   |
| *Hann*     | Highest mother. Goddess of nature and fertility. |
| *Vras*     | God of the dead.                                 |
| *Beatrice* | Goddess of fertility.                            |
| *Nadgaj*   | God of war. God of combat.                       |
*** Secondary Races
**** Mochveneba
Mochveneba or "ghost people" are a minority ethnicity within Naurrnen. They are Aelf-like, in that they share many of the features that elven folk have, but they are well known for their physical prowness. Their skin is a deep red, with stripes. Similar to tiger stripes. In fact, legend outside the Mochveneba tribes, say they are crossbred elves with tigers. In reality, they are more than likely half-breeds. More than likely, half-Aelf, and half-something else. They have unusual stamina, so some speculate half-orc, though their uncommon beauty seems to indicate otherwise.

The Mochveneba tribes are religious, and perhaps to most of the civilized world, somewhat superstitious. Mochveneba are spiritual and do not generally pursue material wealth. Those that do, are coveted for their beauty and brute strength.
***** Strengths
1. Enchanting weapons and items.
2. Known for physical strength.
3. Warlike, but peace-loving.
***** Pantheon
Belief system comprises of the following
1. Animism: They believe spirit is in all things. But they also believe that consciousness is a higher form of spirit.
2. Believe in balance betweem "pah" and "foh". Good/Evil. Hot/Cold, etc.
3. Believe their ancestors live beyond the vale, and they will one day join them in death.
4. Presence, meditation, seeking inner peace and clarity is essential. Past and future, do not matter. Only the present.
5. Cycle of life:  spirit lives and dies, and is renewed again. Consciousness, on the other hand, goes to the ancestral grove, the spirit world, after death, and does not return.

** Languages
*** Adaman, the trade tongue
Adaman is the (almost) universal tongue of Naurrnen. It is used amongst merchants, and mostly widely spoken in everyday communication within the Gran Imperio.
*** Hallashim, language of the Aelves
** Geography
*** Gran Imperio
The human empire. Though many would argue that it is not purely human, but a truly pluralistic and inclusive society. It is an empire with a relatively strong monarchy.
*** Kingdom of Tanquende
Anashim kingdom, primarilly the Hallashim (a.k.a. High Aelves). Territory to the far west of the known world.
*** Vulwin Horde
Nomadic tribes of the Taurashim (Wood Aelves).
*** Tribes of Nigrumia
Tribes of the Orpa (a.k.a the Orcs).
*** Dathakhian Empire
Empire of the Durashim (a.k.a Dark Aelves).
*** Marches of Bounoshin
Home of the Gathashim (the Cavern Aelves or Dwarves). Territory to the far east of the known world.
*** Commonwealth of Caria
Home of the Palama (Pale men, or Nords).
*** Federation of Boignia
Federation of Man (Adama).
*** Principality of Vilesia
Principality of the Durama (a.k.a dark men).
