#+title: Naurnens Lost Origins
#+startup: inlineimages

* Once Upon a Time
A long, long time ago... or was that a long, long time from now? Anyways, in a universe far, far away... or is it a paralell universe that is very near? Anyways, our story begins with an intergalactic civilization, the Setsafar Commonwealth, that has open trade between multiple galaxies, multiple star systems, and multiple intellegent species. The trade routes between galaxies are generally fixed, but every few centuries, there is an economic boom that makes traveling even further distances to further reaches of the universe to find resources for profitable trade.

Given the distance between galaxies and their solar systems, it became expedient to send space stations to un-inhabitable systems for the purpose of refueling, and maintenance of cargo ships. Initially, these stations were sent to orbit various planets in these systems. Profitable enterprises would build these stations, and sell fuel, maintenance and entertainment.

As demand grew for waypoints with lots of trade traffic, these stations would be expanded. Often, in many high traffic stations, these stations were expanded to the size of small moons. Life on a spacestation can be a bit constraining. and limiting in other ways, inspit of holographic enetertainment and virtual reality. There was big business in terraforming inhabitable planets in place of moon stations.

** Setsafar Commonwealth
Setsafar is a commonwealth of multiple nations, tade guilds, and corporations that have been involved with intergalactic trade for well over two thousand years. The commonwealth structures itself around the problems of faster than light speed travel and the time dilations involved with traveling and communicating over vast distances. The coomonwealth has a scale they use to measure time, and they call this scale the Commonwealth timescale. All divergences from this scale are considered time dilations.

* The Terraform Projects
A less costly amd longer sustaining alternative was formed for creating way points along the trade routes. This gave way to terraforming planets to make them habitable. It was far more economic to start a populace on a terraformed planet using incubation pods. Where literally hundreds of thousands of fertilized human and alien embryos could, with the help of non-sentient automotons, be nurtured and grown.

The automotons only covered the biological care of the embryos. Prior to embryo hatching, tutors and educators would arrive and prepare for instructing the new life in how to build its own unique culture and participate in interstellar trade.

The alien races are what the high fantasy reader might identify as men, dwarves, elves, and orcs. There are no explicitly evil races, just very different species each with their own unique gifts, talents, and culture over time.

** Terraform in time
Terraforming can be a long drawn out process, so once a terraform project was set in motion, and an ecological profile for the system to progress into was determined, the planet would  be temporarilly displaced further from gravitational pull to increase the rate in which time passed. Once the planet had progressed far enough in time to begin trade, the planet would be pulled into a much closer time frame that matched the intergalactic standard.

** Terraform process
1. (re)create the planets electro-magnetic field. If this is not easily doable, the planet can be disqualified from being a terraform candidate.
2. Greenhouse domes embark to the planet and the first vegetation is grown in an extremely controlled and managed system.
3. Rocks are pulverized into rich mineral soil, and water is produced, provided the planet has a rich hydrogen atmosphere. Hydrogen can me imported from abroad as needed.
4. Carbon dioxiode from the automosphere is fed in to the plants within the domes, and the oxygen produced is released back into the atmosphere.
5. Plants are systematically replanted into the planets soil. Trees and shrubs soon follow.
6. Robo-insects are release, and begin the process of polinating the plants. Around the same time, the first insect and other animal embryos are brought to the planet and are released in generations, beginning with the smallest animals and moving on to the largest animals. This also includes fish and sea creatures.
7. Human embryos and structures of cities and homes are created on the newly terraformed planet. Non-sentient automotans care for and provide for the humanoid embryos, and even begin nurting, caring for them. The Commonwealth directive states that culture unique to each race should be honored and preserved. The first language of each humanoid must be of that unique to its own race.
8. Once the first humanoid embryos are hatched, senitient beings are sent to adopt and teach the new humanoids how to read, write in the trade tongue of the Commonwealth. As well as their history, and history of the Commonwealth.
9. Once the first humanoids are able to govern themselves, they will be asked to name their planet, as it is no longer a terraform planet. They can engage with trade with the rest of the commonwealth.

* Syscon 37221
Our story begins with the Trade company, Terconi Inc., based on the planet Mercatorma. Terconi named their planet's capital city after the company. They started a risky terraform project on a planet within a system of questionable stability. Terconi's terraform department was named "Syscon" and it was their practice to prefix Syscon to the number associated with the actual project. Thus the project was named "Syscon 37221". The actual official naming of the planet would be left to its new inhabitants after they had matured to the point where they could conduct trade.

When the trade route dried up, the populace was relocated and the planet abandoned. Or so it was thought. Records indicate that there were numerous pods abandoned to the automotons to raise without any monitoring at all. It looks like a bureaucratic cover-up in order to avoid costly relocation of equipment. When the coverup was discovered, a recovery mission was sent in order to re-assume the hatched embryos into society, and possibly recover any equipment that might be salvageable. The system in which the planet was part of was no more. Swallowed up by a neighboring worm hole for sure, it would seem. If the planet still existed, it was unreachable, now.

** The Amearans
When the first embryos from Syscon 37221 hatched, life sustanence and a language was given to them through non-sentient automotans. After the third generation of humanoids had been born, the automatons returned to their docking stations deep underground and shutdown. When the humanoids matured, the planet became known as Naurrnen. But its inhabitants have no idea who they are. They see the technology around them as alien. Some forgotten mysterious civilization that mysteriously disappeared without a trace. They called this civilization, "the Amearans" or "ancient ones".

** Language
Embryos from every known alien race was dispatched to this planet. Automotans gave each race its own cultural language, the common tongue, and a document called the "Rule of Love" or the "Rahnami". The central automotan containing the common language was damaged in transit to the planet and never made it there. Thus the embryos who hatched and grew up only learned their cultural tonog, so there was a divide between races as a result.

** The Rahnami
This Rhanami contained the essential truths common to all races, to begin their journey into symbiotic life. To the Naurrnens, the Rahnami is thought to be an ancient sacred text given to each race by the Amearans. Well, some argue that it was their own unique race that dispatched this truth and translated into the other tongues. Raging debates continue across Naurrnen regarding the Rahnami's origin.
