#+title: The Rahnami
#+startup: inlineimages
#+category: Books

* The Rahnami
Rahnami is the word "first given" to the first inhabitants of Naurrnen. The way the word is pronounced today in the languages of Naurrnen are all similar. But there was a copy of the Rahnami written in each of the indegeneous languages.
** Principles of the Rahnami
*** The first Rahnami is that for love. Love is Rahnami and Rahnami love.
*** Rahnami for others. Rahnami is something that multiplies as it is spent. So always give Rahnami, so that Rahnami will increase.
*** Rahnami for the world. Where there is no Rahnami, there is scarcity. Scarcity is overcome by Rahnami. Resources that cannot be made, must be preserved, and resources that can be made should be shared abundantly.
*** Rahnami is mercy. Before confronting the evil outside, confront the evil in inside. Fix the lack of Rahnami in yourself, and then, and only then can you confront the evil outside. If you want a second chance, give it freely. If you want third, fourth, fifth chance, give it freely. You cannot understand the poverty out there, without first confronting the poverty in here.
*** Rahnami is just. But it is mercy first, and foremost, or it is not just at all.
** King Tasfaye's Commentary on the Principles
1. Principle of Reciprocity: "Treat others as you would be treated, with respect and fairness, regardless of their race or origin."
2. Stewardship of Resources: "Honor and preserve the bounty of our world, using its resources wisely and sustainably for the benefit of all."
3. Justice and Mercy: "Seek justice that restores and heals, balancing retribution with compassion, and punishment with rehabilitation."
4. Seeking Knowledge and Wisdom: "Pursue knowledge and wisdom diligently, for they light the path to understanding and peace among peoples."
5. Fair Exchange and Integrity in Trade: "Engage in trade with honesty and integrity, ensuring that all dealings are fair and benefit all parties."
6. Rights and Responsibilities: "Uphold the rights of all individuals, while also embracing the responsibilities we share to our community and world."
7. Peaceful Coexistence and Conflict Resolution: "Strive for peaceful coexistence and resolve conflicts through wisdom and understanding, not through force or deceit."
