#+title: Technologies of the Setsafar Commonwealth
#+startup: inlineimages
#+include: ../navbar.org
* Technologies of the Setsafar Commonwealth
** Nodus: Intertellar Communication
Nodus is a device made up of
1. Linker
2. Dilation module
3. Lorenza corrector
4. Kill switch

*** Linker
The Linker creates a quantum link between the caller and reciever, and particles are formed on the recieving end forming a completely particle replica of the caller. All bodily sensations such as hearing, seeing, touching, and tasting are transmitted to the reciever.

*** Dilation module
The dilation module dilates the time of the caller to that of the reciever. Only if time frames are synced can meaningful transmission take place. If time dilation is too great, the reciever can also use the dilation module to change their time dilation, forming a less disruptive time dilation medium for both participants. The need for this is rare, and is usually only needed for when traveling hyperspace or for terraform projects, when time dilation differences can sometimes be extreme, depending on the level of terraform progress.

*** Lorenza corrector
The Lorenza corrector can correct both sender and reciever time dilations in cases where such dilations fluctuate. Mostly during hyperspace travel. The Lorenza corrector is set with a max value, at which point the correction is abandoned. This can be necessary when unpredicted circumstances arise during communication.

*** The Kill switch
The kill switch is what disconnects the quantum link between sender and reciever. It activiates on hangup, which may occur when the Lorenza corrector has hit its max setting, or if harmful transmissions are made to the connected reciever from the other end. There is some linking between the communicator and the Kill switch that has to occur to make this possible.

** Gravity Mining
Gravity mining is the process of creating entirely new substances through the use of extremely strong gravitational pull, from the likes of a neutron star or black hole. The easiest manner to describe this process in the real world, is essentially, two particles are bound through quantum mechanics, and once bound, one particle is isolated in a gravity-free container, at absolute zero, and the other is flung into a neutron star or black hole. At a certain point, the linked particle is unlinked, and is something entirely different. What substance you ended up with depended entirely on the starting mass, the gravitational pull of the other particle, the link strength of the two particles, and at which stage the unlinking process begun. The linking and unlinking processes became known as "quantum linking". Because the actual matter being used matters very little, and the abundance of matter to use for the process, and even the ability to recycle the created substances, it is possible to mass produce several entirely new substances. Two of the most common substances produced are Saruleum, a super fuel for space travel, and Baruleum, a metal that can withstand speed of light travel.

*** Saruleum
1. From the ancient tongue (similar to Latin), meaning "blue".
2. Color is silver with streaks of blue light

Saruleum is a soft metal with unusually high levels of electro-magnetism. It is used in lining of fuel tanks for stabilizing anti-matter fuel.

*** Baruleum
A hard and heavy metal. Where Saruleum is used to line a spacecraft's fuel tank, Baruleum is used to line the exterior of the craft to withstand "faster-than-light" travel.
